
version: '3'

volumes:
  mydata:

services:
  app:
    build: .
    # command: npm run dev
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      NODE_ENV: local
      PORT: 3000
      DATABASE_URL: postgres://huser:Passw0rd@db:5432/mydatabase
      TZ: Asia/Tokyo
    depends_on:
      - db
    tty: true
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - mydata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: huser
      POSTGRES_PASSWORD: Passw0rd
      POSTGRES_DB: mydatabase
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      LC_ALL: ja_JP.UTF-8
      LC_CTYPE: ja_JP.UTF-8
      TZ: Asia/Tokyo
    tty: true
